"""Initial migration with all models

Revision ID: 2c7c73d2650e
Revises: 
Create Date: 2025-09-30 06:25:13.594135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c7c73d2650e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('short_id', sa.String(length=8), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('closing_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('admin_token', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_polls')),
    sa.UniqueConstraint('slug', name=op.f('uq_polls_slug'))
    )
    op.create_index(op.f('ix_polls_owner_email'), 'polls', ['owner_email'], unique=False)
    op.create_index(op.f('ix_polls_short_id'), 'polls', ['short_id'], unique=True)
    op.create_table('ballots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('rankings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('write_ins', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('voter_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('voter_token', sa.String(length=64), nullable=True),
    sa.Column('submitted_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('import_batch_id', sa.String(length=100), nullable=True),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_ballots_poll_id_polls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ballots')),
    sa.UniqueConstraint('poll_id', 'voter_fingerprint', name='uq_ballot_fingerprint'),
    sa.UniqueConstraint('poll_id', 'voter_token', name='uq_ballot_token')
    )
    op.create_index(op.f('ix_ballots_poll_id'), 'ballots', ['poll_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('computation_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_results_poll_id_polls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    op.create_index(op.f('ix_results_poll_id'), 'results', ['poll_id'], unique=False)
    op.create_table('voters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('poll_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('invitation_sent', sa.Boolean(), nullable=False),
    sa.Column('invitation_sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_sent_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], name=op.f('fk_voters_poll_id_polls'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_voters')),
    sa.UniqueConstraint('poll_id', 'email', name='uq_voter_poll_email'),
    sa.UniqueConstraint('poll_id', 'email_hash', name='uq_voter_poll_email_hash'),
    sa.UniqueConstraint('token', name=op.f('uq_voters_token'))
    )
    op.create_index(op.f('ix_voters_poll_id'), 'voters', ['poll_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voters_poll_id'), table_name='voters')
    op.drop_table('voters')
    op.drop_index(op.f('ix_results_poll_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_ballots_poll_id'), table_name='ballots')
    op.drop_table('ballots')
    op.drop_index(op.f('ix_polls_short_id'), table_name='polls')
    op.drop_index(op.f('ix_polls_owner_email'), table_name='polls')
    op.drop_table('polls')
    # ### end Alembic commands ###
