"""add_is_test_and_unique_constraint

Revision ID: 93883a4e94c6
Revises: d1afa71fb89d
Create Date: 2025-10-30 17:50:26.926849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93883a4e94c6'
down_revision: Union[str, Sequence[str], None] = 'd1afa71fb89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add is_test column to polls
    op.add_column('polls', sa.Column('is_test', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index('ix_polls_is_test', 'polls', ['is_test'])
    
    # Fix any existing duplicate current results
    op.execute("""
        UPDATE results
        SET is_current = false
        WHERE id IN (
            SELECT r1.id
            FROM results r1
            INNER JOIN (
                SELECT poll_id, MAX(computed_at) as max_computed
                FROM results
                WHERE is_current = true
                GROUP BY poll_id
            ) r2 ON r1.poll_id = r2.poll_id
            WHERE r1.is_current = true
            AND r1.computed_at < r2.max_computed
        )
    """)
    
    # Add unique constraint (IF NOT EXISTS is safe if already on production)
    op.execute("""
        CREATE UNIQUE INDEX IF NOT EXISTS ix_results_poll_id_current_unique 
        ON results (poll_id) 
        WHERE is_current = true
    """)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polls', 'is_test')
    # ### end Alembic commands ###
